language: node_js
node_js:
- '0.12'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GHREPO=github.com/jupyter/jupyter-js-notebook.git
  - secure: jFCmedawvi7eIjq0ONpUJa4KHG+TO6TkCgxvRcVL16vhSEQts7gtvGIqmcbrUGc+wwBy6BE17xw8ijDZrKh3eFO1MPUEVuDGJgJwY1SpBuS4la5FYomKql1J+gy3CddHmcF6cI/NsTw+UlDQsx7c3TUOce+Vp4e2nxXDKA5/q+hhu4zkg/TZSXevaU/LXBjkyYF2kuFib/av7lmOdA/iqd62/D+w9UM8aXTPR/75o82BRIXz+CJXzUTZtLVvFlnmqcqlXMdnVWVNke0y6w3J7x8j/xSXbc++lrfC0/EoiNKRwIMCXqntrYSeG68rgmGjpyFIXcts2/aisa/oYTkG6hzv5Y34G/iBS9iadIon1byajT7Rm/pEjIFwW4mFsrIQEdBlU1NWbEG8UKVd4QVrbSEI1RDC6RAJDTJPMFzKVZIXeaRhn6GupXjr7Tz+8rXFonsMo4zaGDzTU8PvQpAPNW2gbLz0QXVr71YUbXnsV0IbifVML4aWG+4EPpdApKh/+UJVoPe9lCxIbdzIRY9IlN7E++OOAO3rRz6fZfP8AAODyWJyYa0Hofia/l8rYhlA/swoFqJnSyBUSy7a/LXDM4Z3MEyMtPCzILf7GK42lffR28uI94lFHr2MXQ6aIgueV8M2F+BUfGGQhZlfokSJDlsn28bSCun0izaR6f53W6A=
install:
- bash scripts/travis_install.sh
script:
- bash scripts/travis_script.sh
after_success:
- bash scripts/travis_after_success.sh
